DVDGuru.Web/Models/AddEditDVDVM.cs
using DVDGuru.Data;
using DVDGuru.Data.Models;
using DVDGuru.Data.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DVDGuru.Web.Models
{
    public class AddEditDVDVM
    {
        public DVD DVD { get; set; }
        public List<SelectListItem> MPAARatingList { get; set; }
        public List<SelectListItem> UserRatingList { get; set; }

        public AddEditDVDVM()
        {
           // DVDRepository _repo = new DVDRepository();
            DVD = new DVD();
            MPAARatingList = new List<SelectListItem>();
            UserRatingList = new List<SelectListItem>(); 
        }
    }
}

DVDGuru.Web/Models/BorrowerVM.cs
using DVDGuru.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DVDGuru.Web.Models
{
    public class BorrowerVM
    {
        public DVD DVD { get; set; }
        public Borrower Borrower { get; set; }
        public LoanTime LoanTime { get; set; }

        public BorrowerVM()
        {
            DVD = new DVD();
            Borrower = new Borrower();
            LoanTime = new LoanTime();
        }
    }
}

DVDGuru.Web/Controllers/DVDController.cs
using DVDGuru.Data;
using DVDGuru.Data.Models;
using DVDGuru.Web.Models;
using System;
using System.Web.Mvc;


namespace DVDGuru.Web.Controllers
{
    public class DVDController : Controller
    {
        //TODO: rename repos
        private IDVDRepository _repo;
        private IBorrowerRepository _repoBorrower;
        private IMPAARatingRepository _repoMR;
        private IUserRatingRepository _repoUR;
        private ILoanTimeRepository _repoLoanTime;

        public DVDController(IDVDRepository dvdRepository, IBorrowerRepository borrowerRepository, IMPAARatingRepository mpaaRepository, IUserRatingRepository userRatingRepository, ILoanTimeRepository loanTimeRepository)
        {
            _repo = dvdRepository;
            _repoBorrower = borrowerRepository;
            _repoMR = mpaaRepository;
            _repoUR = userRatingRepository;
            _repoLoanTime = loanTimeRepository;
        }

        [HttpPost]
        public ActionResult Search(string title)
        {
            //TODO: check that 'title' isn't null
            var model = _repo.GetSearchedTitles(title);
            return View(model);
        }
        // GET DVD/Details
        public ActionResult Details(int id)
        {
            //TODO: check that 'id' isn't null
            var model = _repo.GetSingleDvd(id);
            return View(model);
        }

        // GET: DVD/Create
        public ActionResult Add()
        {
            //TODO: refactor GetNewDVDVMOrFillLists() to create a new filled VM or take in a parameter
            var model = GetNewDVDVMOrFillLists();
            model.DVD.Available = true;
            return View(model);
        }

        // POST: DVD/Create
        [HttpPost]
        public ActionResult Add(AddEditDVDVM newDVDAddEditViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _repo.Insert(newDVDAddEditViewModel.DVD);
                    return RedirectToAction("Index", "Home");
                }
                catch (Exception)
                {
                    //TODO: Show an error view
                    return View(newDVDAddEditViewModel);
                }
            }
            else
            {
                //TODO: research binding issue
                GetNewDVDVMOrFillLists(newDVDAddEditViewModel);
                return View(newDVDAddEditViewModel);
            }
        }



        private AddEditDVDVM GetNewDVDVMOrFillLists()
        {
            var model = new AddEditDVDVM();
            var mpaaRatings = _repoMR.GetAllMPAARatings();
            var userRatings = _repoUR.GetAllUserRatings();
            foreach (var rating in mpaaRatings)
            {
                SelectListItem newMPAARating = new SelectListItem()
                {
                    Text = rating.MPAARatings,
                    Value = rating.MPAARatingID.ToString()
                };

                model.MPAARatingList.Add(newMPAARating);
            }
            foreach (var uRating in userRatings)
            {
                SelectListItem newUserRatings = new SelectListItem()
                {
                    Text = uRating.Stars.ToString(),
                    Value = uRating.UserRatingID.ToString()
                };

                model.UserRatingList.Add(newUserRatings);
            }
            return model;
        }

        private AddEditDVDVM GetNewDVDVMOrFillLists(AddEditDVDVM emptyAddEditDVDVM)
        {

            var mpaaRatings = _repoMR.GetAllMPAARatings();
            var userRatings = _repoUR.GetAllUserRatings();
            foreach (var rating in mpaaRatings)
            {
                SelectListItem newMPAARating = new SelectListItem()
                {
                    Text = rating.MPAARatings,
                    Value = rating.MPAARatingID.ToString()
                };

                emptyAddEditDVDVM.MPAARatingList.Add(newMPAARating);
            }
            foreach (var uRating in userRatings)
            {
                SelectListItem newUserRatings = new SelectListItem()
                {
                    Text = uRating.Stars.ToString(),
                    Value = uRating.UserRatingID.ToString()
                };

                emptyAddEditDVDVM.UserRatingList.Add(newUserRatings);
            }
            return emptyAddEditDVDVM;
        }


        // GET: DVD/Edit/5
        public ActionResult Lend(int id)
        {
            var model = new BorrowerVM();
            model.LoanTime.LoanDate = DateTime.Now;
            model.DVD = _repo.GetSingleDvd(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Lend(BorrowerVM newBorrower)
        {
            try
            {

                _repoBorrower.Insert(newBorrower.Borrower);
                //TODO: use var dvd
                newBorrower.DVD = _repo.GetSingleDvd(newBorrower.DVD.DVDID);
                newBorrower.DVD.Available = false;
                _repo.Edit(newBorrower.DVD);
                //TODO: use var loanTime
                newBorrower.LoanTime.DVDID = newBorrower.DVD.DVDID;
                newBorrower.LoanTime.BorrowerID = newBorrower.Borrower.BorrowerID;
                _repoLoanTime.Insert(newBorrower.LoanTime);

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View(newBorrower);
            }
        }
        [HttpPost]
        public ActionResult Received(int id)
        {
            try
            {
                var dvd = _repo.GetSingleDvd(id);
                dvd.Available = true;
                _repo.Edit(dvd);
                var loanTime = _repoLoanTime.GetLoanTimeRecord(id);
                //TODO: rename all suffix all DateTime properites with UTC (ie. DateTime.UtcNow)
                //TODO: use DateTime.UtcNow instead of DateTime.Now
                loanTime.ReturnedDate = DateTime.Now;
                _repoLoanTime.ReturnDVD(loanTime);
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                _repo.Delete(id);
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

    }
}

DVDGuru.Web/Controllers/HomeController.cs
using System.Web.Mvc;
using DVDGuru.Data;

namespace DVDGuru.Web.Controllers
{
    public class HomeController : Controller
    {
        private IDVDRepository _repo;

        public HomeController(IDVDRepository dvdRepository)
        {
            _repo = dvdRepository;
        }

        public ActionResult Index()
        {
            return View(_repo.GetAllDVDsList());
        }
    }
}

DVDGuru.Web/Views/DVD/Add.cshtml
@model DVDGuru.Web.Models.AddEditDVDVM

@{
    ViewBag.Title = "Add";
}



<div class="row">
    <div class="col-xs-6">
        <h1>DVD Guru: Add DVD</h1>
        <form action="/DVD/Add" method="post" id="addEditForm">
            @Html.HiddenFor(m=>m.DVD.Available)

            @*@Html.ValidationSummary()*@
            <div class="form-group">
                <p>@Html.ValidationMessageFor(d => d.DVD.Title)</p>
                <label class="control-label">Title</label>
                @Html.TextBoxFor(m => m.DVD.Title, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <p>@Html.ValidationMessageFor(d => d.DVD.ReleaseDate)</p>
                <label class="control-label">Release Date</label><br/>
                @Html.TextBoxFor(m => m.DVD.ReleaseDate, new { @class = "form-control", type = "date" })
            </div>
            <div class="form-group">
                <p>@Html.ValidationMessageFor(d => d.DVD.MPAARatingID)</p>
                <label class="control-label">MPAA Rating</label>
                @Html.DropDownListFor(m => m.DVD.MPAARatingID, Model.MPAARatingList, "-SELECT-", new { @class = "form-control" })
            </div>
            <div class="form-group">
                <p>@Html.ValidationMessageFor(d => d.DVD.DirectorNames)</p>
                <label class="control-label">Director</label>
                @Html.TextBoxFor(m => m.DVD.DirectorNames, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <p>@Html.ValidationMessageFor(d => d.DVD.StudioName)</p>
                <label class="control-label">Studio</label>
                @Html.TextBoxFor(m => m.DVD.StudioName, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <p>@Html.ValidationMessageFor(d => d.DVD.UserRatingID)</p>
                <label class="control-label">User Rating</label>
               @Html.DropDownListFor(m => m.DVD.UserRatingID, Model.UserRatingList, "-SELECT-", new { @class = "form-control" })
            </div>
            <div class="form-group">
                <p>@Html.ValidationMessageFor(d => d.DVD.ActorNames)</p>
                <label class="control-label">Actors</label>
                @Html.TextAreaFor(m => m.DVD.ActorNames, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <p>@Html.ValidationMessageFor(d => d.DVD.UserNote)</p>
                <label class="control-label">Note</label>
                @Html.TextAreaFor(m => m.DVD.UserNote, new { @class = "form-control" })
            </div>
            <button class="btn btn-primary">Save</button>
            @Html.ActionLink("Cancel", "Index", "Home", null, new { @class = "btn btn-warning btn-large" })
        </form>
    </div>
</div>

@section Scripts{
<script src="~/Scripts/jquery.validate.unobtrusive.bootstrap.js"></script>
<script src="~/Scripts/app/jquery-default-validation.js"></script>
<script src="~/Scripts/app/addEditValidation.js"></script>
    }

DVDGuru.Web/Views/DVD/Details.cshtml
@model DVDGuru.Data.Models.DVD
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<head>
<title>DVDGuru: Details</title>
</head>

<div class="container">
    <div class="row">
        <div class="col-xs-6">
        <h3>@Model.Title</h3>
            <p>Release Date: @Model.ReleaseDate.ToString("MM-dd-yyyy")</p>
            <p>Studio: @Model.StudioName</p>
            <p>Actors: @Model.ActorNames</p>
            <p>Director: @Model.DirectorNames</p>
            <p>User Note: @Model.UserNote</p>
            <p>MPAA Rating: @Model.MPAARating.MPAARatings</p>
            <p>User Rating: @for (int i = 0; i < Model.UserRating.Stars; i++)
            {        
                <img src="~/images/star_PNG1592.jpg" />
            } @Model.UserRating.Description </p> 
            @Html.ActionLink("Edit", "Edit", "DVD", new { id = Model.DVDID }, null)
        </div>
    </div>
</div>

DVDGuru.Web/Views/DVD/Edit.cshtml
@model DVDGuru.Web.Models.AddEditDVDVM
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<head>
    <title>DVDGuru: Edit</title>
</head>

<div class="container">
    <div class="row">
        <h3>@Model.DVD.Title</h3>
        <div class="col-xs-6">
            @using (Html.BeginForm("Edit", "DVD", FormMethod.Post, new { id = "addEditForm" }))
            {
                @Html.ValidationSummary()
                @Html.HiddenFor(m=>m.DVD.Available)

                @Html.HiddenFor(m=>m.DVD.DVDID)
                <div class="form-group">
                    <label class="control-label">Title</label>
                    @Html.TextBoxFor(m=>m.DVD.Title, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label class="control-label">Release Date</label>
                    @Html.TextBoxFor(m => m.DVD.ReleaseDate, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date", name = "date" })
                </div>
                <div class="form-group">
                    <label class="control-label">MPAA Rating</label>
                    @Html.DropDownListFor(m => m.DVD.MPAARatingID, Model.MPAARatingList, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label class="control-label">Directors</label>
                    @Html.TextBoxFor(m => m.DVD.DirectorNames, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label class="control-label">Studio</label>
                    @Html.TextBoxFor(m => m.DVD.StudioName, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label class="control-label">User Rating</label>
                    @Html.DropDownListFor(m => m.DVD.UserRatingID, Model.UserRatingList, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label class="control-label">Actors</label>
                    @Html.TextBoxFor(m => m.DVD.ActorNames, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label class="control-label">Note</label>
                    @Html.TextAreaFor(m => m.DVD.UserNote, new { @class = "form-control" })
                </div>
                <button class="btn btn-primary">Save</button>
                @Html.ActionLink("Cancel", "Index","Home", null, new { @class = "btn btn-warning btn-large"})
            }
        </div>
    </div>
</div>
@section Scripts{
    <script src="~/Scripts/jquery.validate.unobtrusive.bootstrap.js"></script>
    <script src="~/Scripts/app/jquery-default-validation.js"></script>
    <script src="~/Scripts/app/addEditValidation.js"></script>
}

DVDGuru.Web/Views/DVD/Lend.cshtml
@model DVDGuru.Web.Models.BorrowerVM

@{
    ViewBag.Title = "Lend";
}

<div class="row">
    <div class="col-xs-6">
       
            <h1>DVD Guru: Lend DVD</h1>
            <h3>@Model.DVD.Title</h3>
        
        @using (Html.BeginForm("Lend", "DVD", FormMethod.Post, new { NewBorrower = Model }))
        {
            @Html.HiddenFor(m => m.DVD.DVDID)
            @Html.HiddenFor(m=>m.Borrower.BorrowerID)
            <div class="form-group">               
                <label class="control-label">First Name</label>
                @Html.TextBoxFor(d => d.Borrower.FirstName, new { @class = "form-control" })
                <label class="control-label">Last Name</label>
                @Html.TextBoxFor(d => d.Borrower.LastName, new { @class = "form-control" })
                <label class="control-label">Borrowed Date</label>
                <br />
                @Html.TextBoxFor(d => d.LoanTime.LoanDate, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                <button class="btn btn-primary">Save</button>
                @Html.ActionLink("Cancel", "Index", "Home", null, new { @class = "btn btn-warning btn-large" })
            </div>
        }

    </div>
</div>

DVDGuru.Web/Views/DVD/Search.cshtml
@model List<DVDGuru.Data.Models.DVD>
@{
    ViewBag.Title = "Search";
}

<h1>Search</h1>

<div class="row">
    <div class="col-xs-12">
        @if (Model.Any())
        {
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Release Date</th>
                        <th>MPAA Rating</th>
                        <th>Stars</th>
                        <th>Availability</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var DVD in Model)
                    {
                        <tr>
                            <td> @Html.ActionLink(DVD.Title, "Details", "DVD", new { id = DVD.DVDID }, null) </td>
                            <td> @DVD.ReleaseDate.ToString("MM-dd-yyyy") </td>
                            <td> @DVD.MPAARating.MPAARatings </td>
                            <td>
                                @for (int i = 0; i < DVD.UserRating.Stars; i++)
                                {
                                    <img src="~/images/star_PNG1592.png" />
                                }
                            </td>
                            <td>
                                @if (DVD.Available == true)
                                {
                                    @Html.ActionLink("Lend", "Lend", "DVD", new { id = DVD.DVDID }, null)
                                }
                                else
                                {
                                    <form action="@Url.Action("Received","DVD", new { id = DVD.DVDID })" method="post">
                                        <button class="btn btn-link" onclick="return confirm('Are you sure you received @DVD.Title?');">Received</button>
                                    </form>
                                }
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", "DVD", new { id = DVD.DVDID }, null)
                            </td>
                            <td>
                                <form action="@Url.Action("Delete","DVD", new {id = DVD.DVDID})" method="post">
                                    <button class="btn btn-danger" onclick="return confirm('Are you sure you want to delete @DVD.Title');">X</button>
                                </form>
                            </td>
                        </tr>

                    }
                </tbody>
            </table>
        }
    </div>
</div>

DVDGuru.Web/Views/Home/Index.cshtml
@model List<DVDGuru.Data.Models.DVD>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-xs-12">
        <h1>DVD Guru: Your DVDs</h1>
        @if (Model.Any())
        {
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Release Date</th>
                        <th>MPAA Rating</th>
                        <th>Stars</th>
                        <th>Availability</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                   @foreach (var DVD in Model)
                   {
                       <tr>
                           <td> @Html.ActionLink(DVD.Title, "Details", "DVD", new { id = DVD.DVDID }, null) </td>
                           <td> @DVD.ReleaseDate.ToString("MM-dd-yyyy") </td>
                           <td> @DVD.MPAARating.MPAARatings </td>
                           <td> @for (int i = 0; i < DVD.UserRating.Stars; i++)
                           {
                                <img src="~/images/star_PNG1592.png" />
                           }
                           </td>
                           <td>
                           @if (DVD.Available == true)
                           {
                               @Html.ActionLink("Lend", "Lend", "DVD", new {id = DVD.DVDID }, null)
                           }
                           else
                           {
                            <form action="@Url.Action("Received","DVD", new { id = DVD.DVDID })" method="post">
                                <button class="btn btn-link" onclick="return confirm('Are you sure you received @DVD.Title?');">Received</button>
                            </form>
                           }
                           </td>     
                           <td>
                             @Html.ActionLink("Edit", "Edit", "DVD", new { id = DVD.DVDID }, null)
                           </td>
                           <td>
                               <form action="@Url.Action("Delete","DVD", new {id = DVD.DVDID})" method="post">
                                   <button class="btn btn-danger" onclick="return confirm('Are you sure you want to delete @DVD.Title');">X</button>
                               </form>
                           </td>
                       </tr>
                    
                   }
                </tbody>
            </table>
        }
    </div>
</div>

DVDGuru.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                    @Html.ActionLink("DVD Guru", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Add DVD", "Add", "DVD", new { area = "" }, new { @class = "navbar-brand" })
                <div class="pull-right">
                    <form action="/DVD/Search" class="navbar-form pull-right" role="search" method="post">
                        <div class="input-group">
                            <input type="text" class="form-control" name="title" id="search" placeholder="Search">
                            <div class="input-group-btn">
                                <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-2.2.3.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>